### ISSUE TITLE
dart-sass deprecated mixed declarations as of 1.77.7

### ISSUE THREAD

**Issue by WardenDrew** [quasarframework/quasar#17364]
### What happened?

On a fresh quasar project a deprecation warning is received for dart-sass.

This deprecation was introduced in the latest version of `dart-sass` 1.77.7 as of today.
https://sass-lang.com/documentation/breaking-changes/mixed-decls/
https://github.com/sass/dart-sass/releases/tag/1.77.7

### What did you expect to happen?

Resolution of deprecation warning.

### Reproduction URL

https://stackblitz.com/edit/quasarframework-vkdssh?file=package.json

### How to reproduce?

1. Go to reproduction link.
2. Run yarn quasar dev
3. Observe deprecation warning

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Platforms/Browsers

Other

### Quasar info output

```Shell
$ yarn quasar info
yarn run v1.22.22
$ C:\Users\AndrewHaskell\source\repos\REDACTED\node_modules\.bin\quasar info

Operating System - Windows_NT(10.0.22621) - win32/x64
NodeJs - 20.15.1

Global packages
  NPM - 10.8.1
  yarn - 1.22.22
  @quasar/cli - undefined
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.16.5 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.9.3 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.16.12 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.4.31 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.4.0
  pinia - 2.1.7 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  vite - 2.9.18 -- Native-ESM powered web dev build tool
  eslint - 8.57.0 -- An AST-based pattern checker for JavaScript.
  electron - Not installed
  electron-packager - Not installed
  @electron/packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*

Networking
  Host - PC-DREW-WORK
  ZeroTier One [e3918db483bd943a] - 10.147.17.8
  Wi-Fi - 10.100.0.46
  vEthernet (Default Switch) - 172.31.144.1

Done in 0.58s.
```

### Relevant log output

```Shell
Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

More info: https://sass-lang.com/d/mixed-decls

     ╷
3424 │ ┌   &--anim
3425 │ │     cursor: wait
     │ └─── nested rule
...  │
3427 │     box-sizing: border-box
     │     ^^^^^^^^^^^^^^^^^^^^^^ declaration
     ╵
    node_modules\quasar\dist\quasar.sass 3427:3  root stylesheet
```

**Comment by rstoenescu** [comment]
Fixed in Quasar v2.16.6

**Comment by rmplbv** [comment]
Not sure if this is the correct spot for this, please excuse if not. 

I'm on 

- "quasar": "^2.16.6",
- "@quasar/app-vite": "^1.9.3",
- "@quasar/cli": "^2.4.1",
- global quasar cli 2.4.1

and I'm still getting the same deprecation warnings. I cleaned build artifacts with `quasar clean` before.

What am I missing?

**Comment by Klikini** [comment]
Same here with Quasar 2.17.0

**Comment by rstoenescu** [comment]
It's not Quasar at fault. The Quasar version has nothing to do with it. It's just the latest Sass which decided to add this warning. See https://github.com/quasarframework/quasar/discussions/17518 for more details.
