### ISSUE TITLE
[ios only?] Flashes / Distortion during scrolling since upgrade to 1.3.0+ (no probl 1.2.7)

### ISSUE THREAD

**Issue by ibrainventures** [quasarframework/quasar#5517]
Thanks for all those great upgrades .. Feeling like Christmas in November :-)

But .. there is something crazy .. (may the dark-side / mode is  calling us ...)

**Describe the bug**
Can only test with touch-device on iOs / Ipad ..

During scrolling the are some "flashes" .. microseconds distortion on the whole
browser-screen. I got some Image elements in a Drawer and there it is best seen.

Cant compare on quasar.dev - site actually not reachable ...

(inside my scrolling content: infinite scroll with images etc.)

npm-ed back to 1.2.7 -> no problem
npm-ed to 1.3.0 -> flashes happen
npm-ed to 1.4.0 -> flashes happen

Many thanks for helping / looking on this Disco-effect ..

**Comment by ibrainventures** [comment]
Update:

tested on the interims dev page:

https://quasardev-jlcbeopeeb.now.sh/vue-components/chat

there is also the flashing .. its not "countable" it happens during scrolling .. 
like a shake-up / refresh / repositining issue .. from / for the all elements / dom

**Comment by pdanpdan** [comment]
What version of iOS, what browser(with version)?

**Comment by ibrainventures** [comment]
Ipad Ios 13.2 u 13.2.2
Safari Browser (with and without request as desktop)

made 2 Videos, may you can "recap" what happens here behind the scene (dom)

https://vimeo.com/371959039

https://vimeo.com/371959857

The Flashing is on the complete Browser Area, not only on the Header element (the vids are not the best)...

**Comment by ibrainventures** [comment]
after getting a wounded touch-finger with testing the quasar docs in ipad landscape mode (as recorded on the vids) the mostly "flashing" pages are:

1. Infinite Scroll
2. Chat Message
3. Video

(from heavy flashy to moderate flashy )

Some other pages only flickers sometimes, some others cant force to flash ..)

**Comment by ibrainventures** [comment]
and after hardcore cross-testing on quasar 1.2.7 .., no flash .. no beep .. no distortion absolute smooth and fine.   going on -> 1.3.0  there it comes ..

**Comment by rstoenescu** [comment]
This should be fixed in "quasar" v1.4.1.

**Comment by ibrainventures** [comment]
Dear @pdanpdan 
dear @rstoenescu 

many thanks for taking a look onto this issue on the holy-weekend.

upgraded our app to 1.4.1, it didnt made any change .. it stills flickers.

After some try-outs, the culprit was found:

Inside the v-slot:loading slot, the `<q-spinner-dots color="primary" size="40px" />`
is making that screen noise ..

Instead of that spinner now using:

` <span>Loading Data...</span>`

Didnt look so fancy, but i need now no more sunglasses on scrolling :-)

May this "out of view-scope animation request" is also occuring other side-effects inside the fw / ios-frontend-rendering ...

**Comment by pdanpdan** [comment]
@ibrainventures Sorry for the request but can you please check if it's still happening with a new Quasar version? Thank you.

**Comment by ibrainventures** [comment]
hi @pdanpdan 

tested on the quasar.dev / documents page in this second. (1.6.1) .. it still flickers on pages like infinite scroll and chat message.

(it still happens through those spinner animations) .. may there are alternative animation-methods or there some webkit-specific animation css rules, which are may more ipados scroll friendly .. (didnt cross check since i excluded the spinner out of my slot)

**Comment by pdanpdan** [comment]
Thank you - I'll check.

**Comment by rstoenescu** [comment]
This should not happen with latest Quasar.
