### ISSUE TITLE
quasar build command strips out necessary quotation marks from index.html - has pr

### ISSUE THREAD

**Issue by ibrainventures** [quasarframework/quasar#7442]
Fresh installed Quasar 

  quasar - 1.12.12 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 2.0.6 -- Quasar Framework local CLI
  @quasar/extras - 1.8.2 -- Quasar Framework fonts, icons and animations

and enter the "quasar build" command. 

The generated target index.html is missing nearly all quotation marks inside the html-s syntax.

Those missing quotation marks around some links are irritating some Browsers. My Firefox 
Edition as example ignores preloading and other got other problems (http-2 prioritising probs).

To make sure that this is no issue of my building-machine, i checked the generated quasar.dev website 
index.html .. there are also no quotation marks.

This must be a longer-time issue, last generated index.html (with v 1.9.x qapp) has also no quotation marks
inside.

![grafik](https://user-images.githubusercontent.com/8803626/87723850-b0aa0b80-c7ba-11ea-9b2c-429be51b18a7.png)

**Comment by ibrainventures** [comment]
i added a pr to this

https://github.com/quasarframework/quasar/pull/7444

**Comment by webnoob** [comment]
It's perfectly valid syntax without quotes so I'm confused as to the problems you're facing.

You should be able to modify this yourself in the quasar conf.

This is the code that registers the plugin:

```js
chain.plugin('html-webpack')
    .use(HtmlWebpackPlugin, [{
      filename: getHtmlFilename(cfg),
      template: appPaths.resolve.app(cfg.sourceFiles.indexHtmlTemplate),
      minify: cfg.__html.minifyOptions,
      templateParameters: templateParam || cfg.htmlVariables,
      chunksSortMode: 'none',
      // inject script tags for bundle
      inject: true,
      cache: true
    }])
```

so you just need to access that plugin in the chain and update the minify options. See: https://github.com/quasarframework/quasar/issues/7433#issuecomment-659207217 for more info on how you need to do it.

**Comment by ibrainventures** [comment]
Hi Allen, thanks for the fast response.

The reason for the issue / my pr was, that we saw yesterday on some of our firefox browsers problems
with the index.html interpreting / http/2 Prorization and with those quotation marks the problems were solved.
(this can also be a issue of mozilla / firefox)

removeAttributeQuotes = true as the default rule is imho to much optimzation - with some pitfalls for the
coverage of the browser-infrastructure against the saving of some bytes.

its more about compatibility and living standard.

**Comment by cbeckford** [comment]
Hi, Quasar noob here,
I am still having this issue in @quasar/app-vite 1.4.6 (@quasar/cli 2.2.3); and it's breaking my Open Graph tags... it's painful to be re-adding the quotes to every tag to fix my index.html file after every build.

**Comment by rstoenescu** [comment]
@cbeckford This will be a non-problem with next major version of q/app-vite (and q/app-webpack as well). Not only we expose the html minify options so you can change them in quasar.config file but for q/app-webpack we also changed the entry point into a comment to avoid all possible issues (just like q/app-vite already does). Will see about some time to backport the exposing of the html minify options.
